[versions]
guava = "33.7.1-jre"
truth = "1.4.0"
dagger = "2.22.1"
autovalue = "1.6.3"
hamcrest = "1.3"

[libraries]
aopalliance = "aopalliance:aopalliance:1.0"
autovalue = { module = "com.google.auto.value:auto-value", version.ref = "autovalue" }
autovalue-annotations = { module = "com.google.auto.value:auto-value-annotations", version.ref = "autovalue" }
bnd = "biz.aQute:bnd:0.0.384"
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-producers = { module = "com.google.dagger:dagger-producers", version.ref = "dagger" }
errorprone-annotations = "com.google.errorprone:error_prone_annotations:2.18.0"
felix-framework = "org.apache.felix:org.apache.felix.framework:3.0.5"
guava = { module = "com.google.guava:guava", version.ref = "guava" }
guava-testlib = { module = "com.google.guava:guava-testlib", version.ref = "guava" }
hamcrest-core = { module = "org.hamcrest:hamcrest-core", version.ref = "hamcrest" }
hamcrest-library = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrest" }
hibernate-core = "org.hibernate:hibernate-core-jakarta:5.6.15.Final"
hsqldb = "org.hsqldb:hsqldb-j5:2.0.0"
jakarta-inject-api = "jakarta.inject:jakarta.inject-api:2.0.1"
jakarta-inject-tck = "jakarta.inject:jakarta.inject-tck:2.0.1"
jakarta-persistence-api = "jakarta.persistence:jakarta.persistence-api:3.0.0"
jakarta-servlet-api = "jakarta.servlet:jakarta.servlet-api:5.0.0"
jspecify = "org.jspecify:jspecify:1.0.1"
jsr305 = "com.google.code.findbugs:jsr305:3.0.1"
junit = "junit:junit:4.13.2"
mockito-core = "org.mockito:mockito-core:4.2.0"
slf4j-simple = "org.slf4j:slf4j-simple:1.6.1"
spring-beans = "org.springframework:spring-beans:5.3.18"
truth = { module = "com.google.truth:truth", version.ref = "truth" }
truth-java8 = { module = "com.google.truth.extensions:truth-java8-extension", version.ref = "truth" }
