name: 'Local Artifact Tests'
description: 'Builds Guice with Maven and runs the example project against the locally installed artifacts.'

runs:
  using: "composite"
  steps:
    - name: 'Set up JDK'
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
      with:
        distribution: ${{ env.USE_JAVA_DISTRIBUTION }}
        java-version: ${{ env.USE_JAVA_VERSION }}
    - name: 'Cache Maven files'
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-artifact-tests-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-artifact-tests-
    - name: 'Delete any stale artifacts from cache'
      run: rm -rf ~/.m2/repository/com/google/inject
      shell: bash
    - name: 'Install local snapshot'
      run: mvn -B install -DskipTests -Dsource.skip=true -Dmaven.javadoc.skip=true
      shell: bash
    - name: 'Maven Java local tests'
      run: |
        GUICE_VERSION=$(mvn -B -q help:evaluate -Dexpression=project.version -DforceStdout)
        mvn -B -f examples/guice-demo/pom.xml verify -Dguice.version="$GUICE_VERSION" --fail-at-end
      shell: bash
    - name: 'Clean up Maven cache'
      run: rm -rf ~/.m2/repository/com/google/inject
      shell: bash
